### ISSUE TITLE
Feature Request: Configure by Biome Name

### ISSUE THREAD

**Issue by PitchBright** [JakobOvrum/BiomeCrops#1]
It would be fantastic to be able to have the option to configure the crops by Biome Name, as well as by Biome Type. When using a mod such as Biomes O Plenty… there are so many biomes that have similar types to one another, but are in reality completely different in terms of being conducive to growing specific crops. Combing a mod like BOP with a mod like HarvestCraft… and used in conjunction with BiomeCrops mod, would allow the user to have fine-grain control over specific crops growing in specific biomes, as opposed the limitless possibilities encountered when configuring by Biome Type.

Is that something you could implement rather easily?

**Comment by JakobOvrum** [comment]
Yeah, it's easy to implement. I was thinking it should have a "whitelist" and a "blacklist" like the current biome type system, where the biomes in the whitelist would be added after resolving the list from the biome types, then biomes from the blacklist removed after that. I think this would allow for fairly complete control.

**Comment by PitchBright** [comment]
That'd be perfect!
