### ISSUE TITLE
Mod doesn't work on SMP server.

### ISSUE THREAD

**Issue by PitchBright** [JakobOvrum/BiomeCrops#6]
The mod works in SSP, and SSP opened to LAN, but doesn't work when used on a SMP server. The SMP server was a fresh install, clean configs. The mod is active, and the /bc info command does work and displays block information. However, the console doesn't show any growth tick events, and the crops won't obey the configs. Also worth noting that the "B:dumpCropBiomeInfo=true" doesn't execute a dump.

**Comment by PitchBright** [comment]
Additional thought, not sure if it matters. I compiled it using Forge 1230, but saw no errors in the console when compiling. I haven't got around to updating my workspace yet, that's why.

The server and clients I've been testing the mod on, are Forge 1291.

**Comment by JakobOvrum** [comment]
dcb864b30c might fix it.

**Comment by PitchBright** [comment]
Yep. You fixed it!
